const stations = {
    Aberporth: 'aberporth',
    Armagh: 'armagh',
    'Ballypatrick Forest': 'ballypatrick',
    Bradford: 'bradford',
    Braemar: 'braemar',
    Camborne: 'camborne',
    'Cambridge NIAB': 'cambridge',
    'Cardiff Bute Park': 'cardiff',
    Chivenor: 'chivenor',
    Cwmystwyth: 'cwmystwyth',
    Dunstaffnage: 'dunstaffnage',
    Durham: 'durham',
    Eastbourne: 'eastbourne',
    Eskdalemuir: 'eskdalemuir',
    Heathrow: 'heathrow',
    Hurn: 'hurn',
    Lerwick: 'lerwick',
    Leuchars: 'leuchars',
    Lowestoft: 'lowestoft',
    Manston: 'manston',
    Nairn: 'nairn',
    'Newton Rigg': 'newtonrigg',
    Oxford: 'oxford',
    Paisley: 'paisley',
    Ringway: 'ringway',
    'Ross-on-Wye': 'rossonwye',
    Shawbury: 'shawbury',
    Sheffield: 'sheffield',
    Southampton: 'southampton',
    'Stornoway Airport': 'stornoway',
    'Sutton Bonington': 'suttonbonington',
    Tiree: 'tiree',
    Valley: 'valley',
    Waddington: 'waddington',
    Whitby: 'whitby',
    'Wick Airport': 'wickairport',
    Yeovilton: 'yeovilton',
};

module.exports = stations;
